version: '3.3'

services:
  api:
    build: .
    container_name: parser_api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=parser_db
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

  mongo:
    image: mongo:6.0
    container_name: parser_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: